### ISSUE TITLE
QLDSK is now Linux compatible

### ISSUE THREAD

**Issue by jonathanlinat** [EnigmaCurry/quake-dev#1]
Hey! I hope you are doing well.

I just found your repository. It looks great as it solves a big problem.

I wanted to let you know that my project is now Linux compatible: https://github.com/jonathanlinat/quake-leveldesign-starterkit

The binaries are built directly from their source code (repository) weekly.

You'll probably need to update your script.

See ya!

**Comment by EnigmaCurry** [comment]
That's Great! I have updated my README to reflect that.

Thanks very much for your hard work and excellent guides.
